### ISSUE TITLE
Staging error when saving to a quoted table name

### ISSUE THREAD

**Issue by marchelleboid** [snowflakedb/spark-snowflake#125]
Version details:
net.snowflake:spark-snowflake_2.11:2.5.0-spark_2.4
net.snowflake:snowflake-jdbc:3.8.4
Spark 2.4.3
Scala 2.11.12

When saving to a Snowflake table whose name is surrounded by double quotes (to preserve case sensitivity), there is an error because of the way the staging table's name is built. You should be able to reproduce the error like this, in spark-shell:

```
import org.apache.spark.sql.SaveMode

val sfOptions = Map(
    "sfURL" -> url,
    "sfUser" -> user,
    "sfPassword" -> password,
    "sfDatabase" -> database,
    "sfSchema" -> schema,
    "sfWarehouse" -> warehouse
)

val df = Seq(
    (1, "one"),
    (2, "two"),
    (3, "three")
).toDF("number", "word")

df.write.format("net.snowflake.spark.snowflake").options(sfOptions).option("dbtable", "\"quoted_name\"").mode(SaveMode.Overwrite).save()
```

The error is:
```
ERROR StageWriter$: Error occurred while loading files to Snowflake: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 13 unexpected '_staging_544555026'.
net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 13 unexpected '_staging_544555026'.
  at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:139)
  at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:64)
  at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:485)
  at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:362)
  at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:502)
  at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:247)
  at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:186)
  at net.snowflake.client.core.SFStatement.execute(SFStatement.java:789)
  at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:245)
  at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:160)
  at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executePreparedQueryInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:248)
  at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executePreparedQueryInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:246)
  at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$1.apply(SnowflakeJDBCWrapper.scala:283)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

It seems to be the way the staging table name is built here: https://github.com/snowflakedb/spark-snowflake/blob/master/src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala#L82. The quotes result in a table name like `"quoted_name"_staging_544555026`, which causes problems in the SQL statement.

This same example works correctly if `usestagingtable` is set to `off` in the `options`.

**Comment by binglihub** [comment]
fixed in 22eba82bdabeee9bcf69c3e5a1746e1672581b0f
