### ISSUE TITLE
Issue when using "name" column_mapping with column names that have periods

### ISSUE THREAD

**Issue by marchelleboid** [snowflakedb/spark-snowflake#131]
Version details:
net.snowflake:spark-snowflake_2.11:2.5.1-spark_2.4
net.snowflake:snowflake-jdbc:3.8.5
Spark 2.4.3
Scala 2.11.12

If you are using a combination of the `column_mapping` parameter set to `name` with a dataframe/table that has column names containing `.`, there is an exception thrown when writing the dataframe. This comes from the `removeUselessColumns` method in `SnowflakeWriter.scala` where it tries to select a new dataframe with only the necessary columns. The simple fix would be to surround each name fed to `dataFrame.select(...)` in `removeUselessColumns` with backticks, though I'm not sure what kind of edge cases will result from doing something like that.

```
import org.apache.spark.sql.SaveMode

val sfOptions = Map(
          "sfURL" -> url,
          "sfUser" -> user,
          "sfPassword" -> password,
          "sfDatabase" -> database,
          "sfSchema" -> schema,
          "sfWarehouse" -> warehouse,
          "keep_column_case" -> "on")

val df = Seq(
    (1),
    (2),
    (3)
).toDF("a.1")

// To create the table
df.write.format("net.snowflake.spark.snowflake").options(sfOptions).option("dbtable", "dot_column").mode(SaveMode.Append).save          

// Turn on column_mapping
val sfOptions = Map(
          "sfURL" -> url,
          "sfUser" -> user,
          "sfPassword" -> password,
          "sfDatabase" -> database,
          "sfSchema" -> schema,
          "sfWarehouse" -> warehouse,
          "column_mapping" -> "name",
          "keep_column_case" -> "on")

// To cause the problem
df.write.format("net.snowflake.spark.snowflake").options(sfOptions).option("dbtable", "dot_column").mode(SaveMode.Append).save
```

And the error:
```
java.lang.IllegalArgumentException: Incorrect column name when column mapping: org.apache.spark.sql.AnalysisException: cannot resolve '`a.1`' given input columns: [a.1];;
'Project ['a.1]
+- Project [value#1 AS a.1#3]
   +- LocalRelation [value#1]

  at net.snowflake.spark.snowflake.SnowflakeWriter.removeUselessColumns(SnowflakeWriter.scala:144)
  at net.snowflake.spark.snowflake.SnowflakeWriter.save(SnowflakeWriter.scala:101)
  at net.snowflake.spark.snowflake.DefaultSource.createRelation(DefaultSource.scala:134)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
  ... 49 elided
```

I also tried using ``"columnmap" -> Map("`a.1`"->"a.1").toString()`` but then you get a different error that field `` `a.1` `` does not exist.

**Comment by Mingli-Rui** [comment]
https://github.com/snowflakedb/spark-snowflake/pull/190
