### ISSUE TITLE
Spark Snowflake Connector Scala version compatibility 

### ISSUE THREAD

**Issue by sherryxhu** [snowflakedb/spark-snowflake#132]
Scala version 2.12.7 
Spark 2.4.2
Spark-Snowflake 2.4.14 

Our application uses the combination of the above three and we use spark-snowflake connector to read data in from Snowflake. Here is the exceptions tag we are having: 

Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at net.snowflake.spark.snowflake.Parameters$MergedParameters.<init>(Parameters.scala:208)
	at net.snowflake.spark.snowflake.Parameters$.mergeParameters(Parameters.scala:202)
	at net.snowflake.spark.snowflake.DefaultSource.createRelation(DefaultSource.scala:59)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)

**Comment by binglihub** [comment]
It may not be Scala compatibility issue. Could you provide some code example can reproduce this issue? thanks

**Comment by binglihub** [comment]
Please download correct connector jar file from https://mvnrepository.com/artifact/net.snowflake/spark-snowflake. 
In your case you should use https://mvnrepository.com/artifact/net.snowflake/spark-snowflake_2.12/2.5.1-spark_2.4.
