### ISSUE TITLE
PySpark: df.write.mode('overwrite') not respected

### ISSUE THREAD

**Issue by DrMcTaco** [snowflakedb/spark-snowflake#138]
### **Current Behavior**
```
df = spark.read.format(sfSource).options(**sfOptions).option('query',  query).load()

df.write.mode('overwrite').format(sfSource).options(**sfOptions).option("dbtable", table).option("parallelism", "15").save()
```
Results in an error:
`Error occurred while loading files to Snowflake: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Object '<TABLE_NAME>' already exists.`

### **Expected Behavior**
 The table is loaded into a spark dataframe and then written to a table in snowflake overwriting any existing data/table with the given table name.

### **Steps to Reproduce**
Run the code snipped in the Current Behavior section 

### **Context (Environment)**

Name | Value
-- | --
Java Version | 1.8.0_222 (Private Build)
Java Home | /usr/lib/jvm/java-8-openjdk-amd64/jre
Scala Version | version 2.11.8

using: `net.snowflake:snowflake-jdbc:3.6.12` and `net.snowflake:spark-snowflake_2.11:2.4.5`

### **Extra Details**
Failed Snowflake Queries (in order):
```desc table identifier(<TABLE_NAME>) ```
```alter table identifier(<TABLE_NAME>_staging_70934098) rename to identifier(<TABLE_NAME>) ```
```drop table identifier(<TABLE_NAME>_staging_70934098) ```

Full stack trace: 
```
Traceback (most recent call last):
  File "/home/ubuntu/data-science-modeling/recommendation_engine/etl_min/etl.py", line 79, in <module>
    main()
  File "/home/ubuntu/data-science-modeling/recommendation_engine/etl_min/etl.py", line 72, in main
    write_to_snowflake(df, "ETL_TEST_1", sfSource, **sfOptions)
  File "/home/ubuntu/data-science-modeling/recommendation_engine/etl_min/etl.py", line 41, in write_to_snowflake
    ).option("parallelism", "8").save()
  File "/home/ubuntu/spark-2.3.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 703, in save
  File "/home/ubuntu/spark-2.3.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/home/ubuntu/spark-2.3.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/home/ubuntu/spark-2.3.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o56.save.
: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Object 'ETL_TEST_1' already exists.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:135)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:60)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:471)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:358)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:473)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:230)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:172)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:661)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:161)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:138)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executePreparedQueryInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:251)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executePreparedQueryInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:249)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$2.apply(SnowflakeJDBCWrapper.scala:286)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Mingli-Rui** [comment]
It is a configuration issue. The right way to set Override is like "df.write.mode(SaveMode.Overwrite)" .
