### ISSUE TITLE
java.util.MissingResourceException: Can't find bundle for base name net.snowflake.client.jdbc.version, locale en_GB 

### ISSUE THREAD

**Issue by VantageKR** [snowflakedb/spark-snowflake#141]
Using the latest (2.5.2), and Snowflake JDBC 3.9, and getting the below both if I build from source or reference them on Maven central:
 
```
java.lang.RuntimeException: Can't load localized resource bundle due to java.util.MissingResourceException: Can't find bundle for base name net.snowflake.client.jdbc.version, locale en_GB and can't load default resource bundle due to java.util.MissingResourceException: C
an't find bundle for base name net.snowflake.client.jdbc.version, locale en_GB
  at net.snowflake.client.jdbc.internal.snowflake.common.core.ResourceBundleManager.reload(ResourceBundleManager.java:69)
  at net.snowflake.client.jdbc.internal.snowflake.common.core.ResourceBundleManager.<init>(ResourceBundleManager.java:37)
  at net.snowflake.client.jdbc.internal.snowflake.common.core.ResourceBundleManager.getSingleton(ResourceBundleManager.java:148)
  at net.snowflake.client.jdbc.SnowflakeDriver.<clinit>(SnowflakeDriver.java:42)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at net.snowflake.spark.snowflake.Utils$.classForName(Utils.scala:59)
  at net.snowflake.spark.snowflake.JDBCWrapper.getConnector(SnowflakeJDBCWrapper.scala:109)
  at net.snowflake.spark.snowflake.SnowflakeRelation$$anonfun$schema$1.apply(SnowflakeRelation.scala:56)
  at net.snowflake.spark.snowflake.SnowflakeRelation$$anonfun$schema$1.apply(SnowflakeRelation.scala:53)
  at scala.Option.getOrElse(Option.scala:121)
  at net.snowflake.spark.snowflake.SnowflakeRelation.schema$lzycompute(SnowflakeRelation.scala:53)
  at net.snowflake.spark.snowflake.SnowflakeRelation.schema(SnowflakeRelation.scala:52)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:403)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
```

**Comment by binglihub** [comment]
We will release a new Spark Connector (2.5.3) today and implement latest JDBC 3.9.1. Please let me know if you still have this issue after upgrade.

**Comment by VantageKR** [comment]
Thanks, and cool; looking forward to it! I have not seen that error since doing this:

```scala
import java.util.Locale
...
Locale.setDefault(Locale.ROOT)
```

Another thing I'm doing is to add all the JDBC driver jars to the `--jars` argument for spark-shell, as well as have them included in the fat jar of my application. I do suspect that similarly named files for different JDBC drivers cause problems in the fat jar, built with the assembly task in SBT since SBT emits that files were discarded due to merge conflicts. Any advice on how to still have the convenience of a fat jar, and how to overcome this issue when you want to bundle multiple storage tech  JDBC drivers perhaps? My fat jar + add on classpath approach seems to be working, and it has the advantage of taking care of dependancies that do not clash in that same way - otherwise I'd have to have such a massive `--jars` argument. There will probably be trouble ahead when I get to the spark-submit way of submitting the application to the cluster, but I'll cross that bridge when I get there... Thanks again.
