### ISSUE TITLE
Writing on empty df is throwing exception java.util.NoSuchElementException: head of empty list

### ISSUE THREAD

**Issue by rkesh-singh** [snowflakedb/spark-snowflake#148]
**Repro:**
spark.read is returning empty df  invoke write on the same data frame is throwing an exception 

scala> val df = spark.read.format(SNOWFLAKE_SOURCE_NAME).options(sfOptions).option("query", "select * from PERSONS_READ where
 personid=1200").load()
df: org.apache.spark.sql.DataFrame = [NAME: string, PERSONID: decimal(38,0)]

scala> df.show
+----+--------+
|NAME|PERSONID|
+----+--------+
+----+--------+

scala> df.write.format(SNOWFLAKE_SOURCE_NAME).options(sfOptions).option("dbtable","PERSONS_TGT").mode(SaveMode.Append).save()
;
java.util.NoSuchElementException: head of empty list
  at scala.collection.immutable.Nil$.head(List.scala:420)
  at scala.collection.immutable.Nil$.head(List.scala:417)
  at net.snowflake.spark.snowflake.io.StageWriter$.writeToStage(StageWriter.scala:59)
  at net.snowflake.spark.snowflake.io.package$.writeRDD(package.scala:53)
  at net.snowflake.spark.snowflake.SnowflakeWriter.save(SnowflakeWriter.scala:103)
  at net.snowflake.spark.snowflake.DefaultSource.createRelation(DefaultSource.scala:134)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:654)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
  ... 49 elided

**Comment by rkesh-singh** [comment]
snowflake-jdbc 3.8.6 
spark-snowflake_2.11 2.5.1-spark_2.4

**Comment by Mingli-Rui** [comment]
https://github.com/snowflakedb/spark-snowflake/commit/9b83f61f48588863b05d1190717c801dfafe201f

**Comment by Mingli-Rui** [comment]
It has been fixed.

**Comment by rkesh-singh** [comment]
@Mingli-Rui What is the fixed version?
