### ISSUE TITLE
java.lang.IllegalArgumentException: Don't know how to save StructField(SSN,BinaryType,true) of type SSN to Snowflake

### ISSUE THREAD

**Issue by VantageKR** [snowflakedb/spark-snowflake#155]
This exception is thrown when reading from a SQL Server table, and saving to Snowflake, where the column named SSN is of data type NVARCHAR with collation set to "Latin1_General_BIN2".
Note that other tables, with columns of data type NVARCHAR, but with collation set to "S" persists without any issues.
This might be a Snowflake JDBC issue, and if so, please raise/reassign on the Snowflake JDBC repo.

Here is more exception details:

```

**Comment by VantageKR** [comment]
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.IllegalArgumentException: Don't know how to save StructField(SSN,BinaryType,true) of type SSN to Snowflake
	at net.snowflake.spark.snowflake.JDBCWrapper.schemaConversion(SnowflakeJDBCWrapper.scala:218)
	at net.snowflake.spark.snowflake.Utils$$anonfun$containVariant$1.apply(Utils.scala:441)
	at net.snowflake.spark.snowflake.Utils$$anonfun$containVariant$1.apply(Utils.scala:441)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at net.snowflake.spark.snowflake.Utils$.containVariant(Utils.scala:441)
	at net.snowflake.spark.snowflake.SnowflakeWriter.save(SnowflakeWriter.scala:70)
	at net.snowflake.spark.snowflake.DefaultSource.createRelation(DefaultSource.scala:134)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)


```

**Comment by VantageKR** [comment]
Sorry, the collation on NVARCHAR columns that succeed is: "SQL_Latin1_General_CP1_CI_AS".

**Comment by Mingli-Rui** [comment]
The source column type in MS SQL server is NVARCHAR, when spark reads the NVARCHAR type column, it should be 'StringType' in spark. So the root cause should be that why the MS NVARCHAR type is read as 'BinaryType' not 'StringType'. This is out of the scope of Snowflake connector. Please contact Snowflake support engineering, if more diagnostic information indicates this is a snowflake connector issue.
PS: Snowflake connector will be enhanced to support 'BinaryType', and it is a separate story.

**Comment by VantageKR** [comment]
Thanks @Mingli-Rui, and I agree that it is out of scope for Snowflake Connector: the Spark type should be String but the collation throws it off, so it's probably the MS SQL Server connector - will post there and reference here. Cool that binary column data type is in the works! We actually would love that right now. Any idea when this will be available?
