### ISSUE TITLE
Support for Binary types

### ISSUE THREAD

**Issue by kerinin** [snowflakedb/spark-snowflake#20]
We have tables that consist mainly of MD5 hashes, storing them as strings basically doubles the size on disk.  It would be very nice if we could read these tables into Spark.

See:
https://github.com/snowflakedb/spark-snowflake/blob/master/src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala#L324

**Comment by dzlab** [comment]
Still cannot read read tables with `BINARY` type, if i do the following
```scala
val df = sqlContext
  .read
  .format(SNOWFLAKE_SOURCE_NAME)
  .options(sfOptions())
  .load()
df.collect()
```
Then I get this exception:
```
java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getBinary(rows.scala:47)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getBinary(rows.scala:195)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:256)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Mingli-Rui** [comment]
Binary types have been supported from Spark Connector 2.6.0
