### ISSUE TITLE
Unable to get data to snowflake with binary columns correctly

### ISSUE THREAD

**Issue by NiharGharat** [snowflakedb/spark-snowflake#209]
Hi,
I am trying to read and write data from/to snowflake using spark. I am unable to read data correctly, and this causes issue while writing data back to snowflake on binary columns. I am creating a dataset<Row> and writing it back to different table.
The dataset created has correct schema, dataset.show() fetched correct values but Row[] created using select has incorrect values in it. I have tried with HEX, BASE64 and UTF encoding in snowflake output format as per below linked doc.
eg - 
```
dataset.show()
+-------------+
|            B|
+-------------+
|[48 45 4C 50]|
+-------------+
(Row[]) dataset.select("B").head(10);
- row - 1
0 - [[B@7fc9d2f5], StructType(StructField(B,BinaryType,true))
	- value - [72, 69, 76, 80]
```
// Steps to reproduce
1. Referring to this [doc](https://docs.snowflake.com/en/user-guide/binary-input-output.html), 
```
ALTER User SET BINARY_OUTPUT_FORMAT = 'HEX';
ALTER User SET BINARY_INPUT_FORMAT = 'HEX';
create table db.sch.demo_binary_hex (b binary);

insert into db.sch.demo_binary_hex (b) select to_binary(hex_encode('HELP'), 'HEX');

select * from db.sch.demo_binary_hex;
select to_varchar(b), hex_decode_string(to_varchar(b)) from db.sch.demo_binary_hex;
```
2. create dataset<Row> with spark in java
```
dataset = dataframeReader.format(sourceName).options(sfOptions)
					.option("query", queryAlias.toString()).load();
dataset.show();
+-------------+
|            B|
+-------------+
|[48 45 4C 50]|
+-------------+
// Row[]
(Row[]) dataset.select("B").head(10)
0 - [[B@2674b632], StructType(StructField(B,BinaryType,true))
          - [72, 69, 76, 80]
```
3. pass this dataset to writer
```
DataFrameWriter<Row> dataframeWriter = dataset.write();
dataframeWriter.format(sourceName).options(sfOptions)
					.option("dbtable", notCreatedTable).mode(SaveMode.Append).save();
// Overwrite also dosent work
// Append creates table but exception when inserting data
```

exception - 
`SnowflakeUtil.checkErrorAndThrowExceptionSub(JsonNode, boolean) line: 152`
```
String '[B@2674b632' is not a legal hex-encoded string
  File 'LzW5juDOmh/0.CSV.gz', line 1, character 1
  Row 1, column "DEMO_BINARY_HEX_1_STAGING_1359460749"["B":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
```

trace
```
net.snowflake.client.jdbc.SnowflakeSQLException: String '[B@2674b632' is not a legal hex-encoded string
  File 'LzW5juDOmh/0.CSV.gz', line 1, character 1
  Row 1, column "DEMO_BINARY_HEX_1_STAGING_1359460749"["B":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:152)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:77)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:495)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:372)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:575)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:265)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:203)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:874)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:259)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:181)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executePreparedQueryInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:317)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executePreparedQueryInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:315)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$1.apply(SnowflakeJDBCWrapper.scala:355)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
// Additional
I have tried with base64 input output, but it gives same exception, also utf8 although snowflake dosent let to set output format to utf8.
https://docs.snowflake.com/en/user-guide/binary-input-output.html
https://docs.snowflake.com/en/sql-reference/parameters.html#binary-input-format
I am using java8, spark 2.3.1, and net.snowflake.spark-snowflake_2.11 2.6.0-spark_2.3
This is on snowflake 4.11.2

**Comment by sfc-gh-mrui** [comment]
@NiharGharat This has been supported from spark connector 2.7.1. Could you please try new version of Spark Connector?  https://github.com/snowflakedb/spark-snowflake/releases/tag/v2.7.1-spark_2.4
