### ISSUE TITLE
Expired S3 Tokens

### ISSUE THREAD

**Issue by KJCrawford** [snowflakedb/spark-snowflake#21]
We're trying to run some spark code on an AWS EMR instance and we get the following error that usually occurs around the ~45 minute mark. We've messed around with a handful of config options, but we haven't been able to nail anything down. 

The configuration we're having is:

> [{"classification":"spark-env", "properties":{}, "configurations":[{"classification":"export", "properties":{"PYSPARK_PYTHON":"python34"}, "configurations":[]}]},{"classification":"spark-defaults", "properties":{"spark.executor.memory":"10G", "spark.yarn.executor.memoryOverhead":"10G"}, "configurations":[]}]

The step we're running is:
> spark-submit --deploy-mode cluster --packages com.amazonaws:aws-java-sdk-s3:1.11.269,net.snowflake:spark-snowflake_2.11:2.2.8,org.apache.hadoop:hadoop-aws:2.7.2 --py-files s3://helper_functions.zip s3://py_file.py

The error code we're getting on each individual node is is:
> 18/01/27 21:52:26 WARN TaskSetManager: Lost task 0.0 in stage 8.0 (TID 627, ip-10-0-16-5.ec2.internal, executor 8): com.amazonaws.services.s3.model.AmazonS3Exception: The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken; Request ID:request_id; S3 Extended Request ID: request_id), S3 Extended Request ID: request_id
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1398)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1259)
	at net.snowflake.spark.snowflake.SnowflakeRDD$$anonfun$compute$1.apply(SnowflakeRDD.scala:115)
	at net.snowflake.spark.snowflake.SnowflakeRDD$$anonfun$compute$1.apply(SnowflakeRDD.scala:90)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at net.snowflake.spark.snowflake.SnowflakeRDD.compute(SnowflakeRDD.scala:90)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by etduwx** [comment]
Hi @KJCrawford, 

Thanks for reaching out. We are aware of this issue for certain long-running jobs, and would like to work on a fix in the long term. 

At the moment, there are two workarounds: (1) we can increase the lifespan of the scoped credentials for you via a parameter (which comes with its own security disclaimer -- reach out to support if you want this done), and (2) via use of your own S3 bucket for data staging (using the `tempDir` parameter in the connector, which means you provide your own S3 target, and AWS keys).

**Comment by KJCrawford** [comment]
Thanks @etduwx.

https://github.com/snowflakedb/spark-snowflake/blob/9fc3e352f8709f2adcbcf35b048436b6e7999f5c/src/main/scala/net/snowflake/spark/snowflake/Parameters.scala#L112-L116

There's a note that this `tempDir` feature is depreciated. Is the plan for this feature to at least stick around until the long-running job issue is fixed?

**Comment by etduwx** [comment]
@KJCrawford: Yes, for sure.
