### ISSUE TITLE
net.snowflake.client.jdbc.SnowflakeSQLException: No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

### ISSUE THREAD

**Issue by rishi-j** [snowflakedb/spark-snowflake#30]
USING:
"net.snowflake" %% "spark-snowflake" % "2.3.1-spark_2.1"

    val sfOptions = Map(
      "sfURL" -> SNOWFLAKE_URL,
      "sfAccount" -> SNOWFLAKE_ACCOUNT,
      "sfUser" -> SNOWFLAKE_USER,
      "sfPassword" -> SNOWFLAKE_PASSWORD,
      "sfDatabase" -> sfDatabase,
      "sfRole" -> SNOWFLAKE_ROLE,
      "sfSchema" -> sfSchema,
      "sfWarehouse" -> SNOWFLAKE_WAREHOUSE,
      "dbtable" -> sfTable
    )

    df.write
      .format("net.snowflake.spark.snowflake")
      .options(sfOptions)
      .mode(SaveMode.Append)
      .save()

THROWS:

ERROR SnowflakeWriter: Error occurred while loading files to Snowflake: net.snowflake.client.jdbc.SnowflakeSQLException: No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

Exception in thread "main" net.snowflake.client.jdbc.SnowflakeSQLException: No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:99)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:410)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:373)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:197)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:149)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:531)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:204)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:239)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:261)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(SnowflakeJDBCWrapper.scala:261)
	at net.snowflake.spark.snowflake.JDBCWrapper$$anonfun$3.apply(SnowflakeJDBCWrapper.scala:283)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by etduwx** [comment]
Hi @rishi-j -- Could you ensure that the warehouse you have selected in sfWarehouse exists and is visible to the selected account and user? Thanks.

**Comment by rishi-j** [comment]
Hi @etduwx 
 Yes the warehouse and the user exists. I am able to write data directly from the jdbc connector when I use the same config file. For some reason when I do it with spark-snowflake, it throws me this error.

**Comment by ouyang0** [comment]
was there ever a fix/workaround for this error?
