### ISSUE TITLE
Error writing into Snowflake when there is a Map type column in the DataFrame 

### ISSUE THREAD

**Issue by josepmv** [snowflakedb/spark-snowflake#319]
Hello,

We have found two bugs (that are related) using the Snowflake-connector when writing a Spark Dataframe into Snowflake when a column is a map type: 
1. and another column has a SQL keyword at the end (i.e. "born for", `FOR` is a keyword): it fails.
2. and another column has a space (the kind of column name that in SQL in Snowflake you would write "between quotes"): it doesn't fail but the column values all are NULL.

We are using the Snowflake connector in Databricks using pyspark. The version used is `snowflake-connector: 2.8.1-spark_3.0` because it's the version available from DBR [7.2](https://docs.databricks.com/release-notes/runtime/7.2.html), to [7.5 Beta](https://docs.databricks.com/release-notes/runtime/7.5.html). But checking the release notes of newer versions of the snowflake-connector it looks like that this bug hasn't been solved.

# Code to reproduce it

We have been able to create a synthetic test to reproduce the bugs.

#### To create the dataframe

```python

SNOWFLAKE_SOURCE_NAME = "net.snowflake.spark.snowflake"
data = [("Bob", 23, {"likes": "play guitar", "from": "Europe"}, "running"), ("Alice", 54, {"eyes": "brown", "living": "UK"}, "painting")]
df = spark.createDataFrame(data, ["name", "age", "some_data", "born for"])

```

#### This fails because has a map column and a column that uses a SQL keyword at the end

Writing the above Spark Dataframe in Snowflake when a column is a map and another column has a SQL keyword it fails. Depending the keyword used, we have one error or another. In this case:

```
Py4JJavaError: An error occurred while calling o322.save.
: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 1 at position 199 unexpected 'for'.
```

Code:

```python
(df.write.format(SNOWFLAKE_SOURCE_NAME)
    .options(**sf_options)
    .option("dbtable", "reproduce_snowflake_connector_bug" )
    .mode('Overwrite')
    .save())
```

#### If we don't insert the map column `some_data`: it works and the right data is in Snowflake

```python
(df.select(["name", "age", "born for"])
    .write.format(SNOWFLAKE_SOURCE_NAME)
    .options(**sf_options)
    .option("dbtable", "reproduce_snowflake_connector_bug" )
    .mode('Overwrite')
    .save())
```

#### If we keep the map column and we rename the `born for` to `for born` it doesn't fail but in Snowflake the column has all values NULLs

This test is to show that just swapping the two words the behavior changes: when the column is name `born for` it fails in pyspark. While `born for` doesn't give an error but we don't get the data in Snowflake (all NULL values).

```python
(df.withColumnRenamed('born for','for born')
    .write.format(SNOWFLAKE_SOURCE_NAME)
    .options(**sf_options)
    .option("dbtable", "reproduce_snowflake_connector_bug" )
    .mode('Overwrite')
    .save())
```

#### If we keep the map column and we rename the `born for` to `born fooor` it doesn't fail but in Snowflake the column has all values NULLs

This is to show that if the column name has no keywords, but requires a "quote column name" we get NULL values in Snowflake.

```python
(df.withColumnRenamed('born for','born fooor')
    .write.format(SNOWFLAKE_SOURCE_NAME)
    .options(**sf_options)
    .option("dbtable", "reproduce_snowflake_connector_bug" )
    .mode('Overwrite')
    .save())
```

#### If we keep the map column and we rename the `born for` to `born_fooor` then it works and Snowflake has the correct data

```python
(df.withColumnRenamed('born for','born_fooor')
    .write.format(SNOWFLAKE_SOURCE_NAME)
    .options(**sf_options)
    .option("dbtable", "reproduce_snowflake_connector_bug" )
    .mode('Overwrite')
    .save())
```

**Comment by josemanuel-hita** [comment]
Hello!

I have a related issue, and I think they both have the same origin.

I’ve created two tables

CREATE TABLE "TABLE_TEST1” ("ID" INT NULL, "TA$BLE" CHAR(15) NULL);
CREATE TABLE "TABLE_TEST2” ("ID" INT NULL, "TA$BLE" CHAR(15) NULL);

And I’m trying to copy data from one to another through a DataFrame. I’m getting the next error:

Caused by: java.lang.UnsupportedOperationException:
can't find column "TA$BLE" in Snowflake Table
	at net.snowflake.spark.snowflake.Utils$$anonfun$generateColumnMap$3.apply(Utils.scala:613)
	at net.snowflake.spark.snowflake.Utils$$anonfun$generateColumnMap$3.apply(Utils.scala:610)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
	at net.snowflake.spark.snowflake.Utils$.generateColumnMap(Utils.scala:610)
	at net.snowflake.spark.snowflake.Parameters$MergedParameters.setColumnMap(Parameters.scala:696)
	at net.snowflake.spark.snowflake.SnowflakeWriter.save(SnowflakeWriter.scala:68)
	at net.snowflake.spark.snowflake.DefaultSource.createRelation(DefaultSource.scala:137)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)

I think the connector is reading properly the column names, but it fails when trying to mapping the columns to the destination table (it seems related to column quoting). 

The version I used: snowflake-connector: 2.9.3-spark_2.4

**Comment by josemanuel-hita** [comment]
Hello,

I can see this issue as completed, but I can't see any information about it (no assignees, no development branch...). Could you please confirm if the issue has been fixed?

Thank you!
