### ISSUE TITLE
SnowflakeWriter fails when table does not yet exist and column_mapping is set as "name"

### ISSUE THREAD

**Issue by tmszk** [snowflakedb/spark-snowflake#377]
Used `spark-snowflake_2.12_2.8.3-spark_3.0` & `spark-snowflake_2.12_2.9.1-spark_3.1` ..

When writing a spark df to snowflake using option "column_mapping" = "name", the process will fail when the table does not yet exist:
````
21/09/19 10:16:50 INFO SparkContext: SparkContext already stopped.
...
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executeInterruptibly$2(SnowflakeJDBCWrapper.scala:351)
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executePreparedQueryInterruptibly$1(SnowflakeJDBCWrapper.scala:313)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:117)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:639)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:743)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:134)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:197)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:486)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:345)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:442)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
Object 'REPORT_AGGREGATED_STREAMING_METRICS' does not exist or not authorized.
Exception in thread "main" net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
````

This seems like a bug to me because:
- The SnowflakeWriter supports table creation when tables do not yet exist, for all SaveModes.
- When using SaveMode "Append" you want to set column_mapping to "name" for incremental loads. It is strange that for this use case you would need to create a table yourself, apply a work-around or deploy different code for the first run (with column_mapping as "order").
- A work-around where you use option columnmap instead and pass all the spark columns explicitly (`.option("columnmap", df.columns.map(col => (col, col)).toMap.toString)`) does work. 
Setting "columnmap" is what the SnowflakeWriter does under the hood for "column_mapping" so I would expect the behaviours to be the same.

It seems the root cause for the issue is that option "column_mapping" pings the table before tables are generated if necessary within _io.writeRDD_:
````
private[snowflake] class SnowflakeWriter(jdbcWrapper: JDBCWrapper) {

  def save(sqlContext: SQLContext,
           data: DataFrame,
           saveMode: SaveMode,
           params: MergedParameters): Unit = {
           ...
if (params.columnMap.isEmpty && params.columnMapping == "name") {
      val conn = jdbcWrapper.getConnector(params)
      try {
        val toSchema: Option[StructType] = Some(
          Utils.removeQuote(
            jdbcWrapper.resolveTable(conn, params.table.get.name, params) --> pings table
          )
        )
        params.setColumnMap(Option(data.schema), toSchema)
      } finally conn.close()
    }
    ...
    io.writeRDD(params, strRDD, output.schema, saveMode, format) --> creates tables if not exists
```

**Comment by sfc-gh-mrui** [comment]
@tmszk This sounds more like a user error instead of a bug. `"column_mapping" = "name"` tells the connector to map columns based on table's column names. It implicitly indicates the table should exist. Since you have a workaround for your use case. I will close this issue. https://docs.snowflake.com/en/user-guide/spark-connector-use.html
