### ISSUE TITLE
Snowflake JDBC Driver fails when the schema is 255 characters long

### ISSUE THREAD

**Issue by josemanuel-hita** [snowflakedb/spark-snowflake#411]
Hello,

I'm having a problem related to long schema names using the Snowflake connector.

For a schema name 255 characters long, the Snowflake API returns the following response, even though the Snowflake official documentation (https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html) specifies that object names up to 255 characters are allowed:

```
ERROR Error response: HTTP Response code: 400, request: POST 
https://...snowflakecomputing.com:443/session/v1/login-request?databaseName=...&schemaName=...&warehouse=...&requestId=… HTTP/1.1

ERROR Error executing request: POST https://...snowflakecomputing.com:443/session/v1/login-request?databaseName=...&schemaName=...&warehouse=..&requestId=… HTTP/1.1 

ERROR Response status line reason: Bad Request 
ERROR Response content: Not a valid SQL Identifier. 
```

This is the stack trace of the thrown Exception:

```
net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: HTTP status=400.
	at net.snowflake.client.core.HttpUtil.executeRequestInternal(HttpUtil.java:664)
	at net.snowflake.client.core.HttpUtil.executeRequest(HttpUtil.java:584)
	at net.snowflake.client.core.HttpUtil.executeGeneralRequest(HttpUtil.java:551)
	at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:587)
	at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:285)
	at net.snowflake.client.core.SFSession.open(SFSession.java:457)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:104)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
	at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:172)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at net.snowflake.spark.snowflake.JDBCWrapper.getConnector(SnowflakeJDBCWrapper.scala:209)
	at net.snowflake.spark.snowflake.Utils$.getJDBCConnection(Utils.scala:277)
```

Besides this, when I double-quote the schema name, it fails with the same error for names longer than 252 characters, as if the quotes are being counted as part of the name.

I tested other object names, such as table or column names, and it works properly with or without double quotes for the specified maximum length of 255 characters.

snowflake-connector versions:
- 2.7.0-spark_2.4
- 2.9.3-spark_2.4

**Comment by josemanuel-hita** [comment]
Hello,

I can see this issue as completed, but I can't see any information about it (no assignees, no development branch...). Could you please confirm if the issue has been fixed?

Thank you!

**Comment by sfc-gh-mrui** [comment]
@josemanuel-hita Thanks for report this issue. I can reproduce this issue. The error is reported when SC uses JDBC to connect to Snowflake. A Jira has been filed for JDBC team. https://snowflakecomputing.atlassian.net/browse/SNOW-647217
