### ISSUE TITLE
Can't load data from S3 in spark after adding spark-snowflake connector Jar to job

### ISSUE THREAD

**Issue by ctivanovich** [snowflakedb/spark-snowflake#430]
Somehow, the addition of the connector interferes with the usual packages used by Spark for reading/writing to S3. I get this error when reading from S3, using spark 3.2.1, and the corresponding jars needed for S3:
- hadoop-aws-3.2.1.jar
- aws-java-sdk-bundle-1.11.563.jar

and the appropriate version of the connector:
- spark-snowflake_2.13-2.10.0-spark_3.2.jar

as well as the jdbc driver:
- snowflake-jdbc-3.9.2.jar

```
> spark.read.parquet("s3a://some-bucket/some-partitioned-table")

Py4JJavaError: An error occurred while calling o71.parquet.
: java.lang.NoClassDefFoundError: scala/$less$colon$less
	at net.snowflake.spark.snowflake.DefaultSource.shortName(DefaultSource.scala:44)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$18.apply(DataSource.scala:630)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$18.apply(DataSource.scala:630)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:630)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.$less$colon$less
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 25 more
```

I've confirmed I can load from S3 without issue once I remove the snowflake connector. 

Thank you for your help!

**Comment by sfc-gh-mrui** [comment]
@ctivanovich It looks it is a configuration issue.
1. I don't think JDBC 3.9.2 could work with Spark Connector 2.10.0. I think you needs to use JDBC `3.13.14` https://mvnrepository.com/artifact/net.snowflake/spark-snowflake_2.13/2.10.0-spark_3.2
2. You need to choose the Spark connector based on your spark version. what's scala version for your spark? The spark connector you choose is for scala 2.13. If your spark is 2.12, you may see this error.

**Comment by sfc-gh-mrui** [comment]
Please open again if your spark is scala 2.13.
