### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by yuzhangyi** [snowflakedb/spark-snowflake#436]
When we use snowflake as sink to write data, it is failed with following error, could you help give guidance to us? Thanks.

The spark-snowflake version we used is: "net.snowflake" %% "spark-snowflake" % "2.6.0-spark_2.4"

DF-SYS-01 **at Sink 'tgtcirruspvsninvoicefact': java.util.ConcurrentModificationException**
java.util.ConcurrentModificationException
	at java.util.HashMap.forEach(HashMap.java:1293)
	at net.snowflake.client.jdbc.SnowflakeChunkDownloader.terminate(SnowflakeChunkDownloader.java:756)
	at net.snowflake.client.core.SFArrowResultSet.close(SFArrowResultSet.java:615)
	at net.snowflake.client.jdbc.SnowflakeResultSetV1.close(SnowflakeResultSetV1.java:133)
	at net.snowflake.client.jdbc.SnowflakeResultSetV1.close(SnowflakeResultSetV1.java:127)
	at net.snowflake.spark.snowflake.SnowflakeRelation.getSnowflakeResultSetRDD(SnowflakeRelation.scala:208)
	at net.snowflake.spark.snowflake.SnowflakeRelation.getRDD(SnowflakeRelation.scala:158)
	at net.snowflake.spark.snowflake.SnowflakeRelation.buildScan(SnowflakeRelation.scala:146)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:285)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:285)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:318)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:317)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:395)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:313)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:281)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:67)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:67)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)

**Comment by yuzhangyi** [comment]
@sfc-gh-jfan , could you help have a look at this case and give some guidance? At the same time, github-actions bot automatically close the case even it is not resolved.

**Comment by yuzhangyi** [comment]
@sfc-gh-jfan, could you help give some guidance to workaround up issue? Our customers are waiting for the update daily, thanks.

**Comment by yuzhangyi** [comment]
@sfc-gh-jfan , this is kind ping, could you help give some update about this case? Thanks.

**Comment by sfc-gh-mrui** [comment]
@yuzhangyi I think this issue has been fixed in newer Spark connector version. The issue happened when spark connector driver to close the result set, this exception can be ignored since spark connector use a different way to read the result.

**Comment by yuzhangyi** [comment]
@sfc-gh-mrui , could you share this fix is included in which snowflake-spark-sdk version? At the same time, could you share how we can ignore the error (by write code) and not fail write data operation.

**Comment by sfc-gh-mrui** [comment]
@yuzhangyi `net.snowflake.spark.snowflake.SnowflakeRelation.getSnowflakeResultSetRDD` executes the query. The JDBC will prefetch the result chunks in background threads. This issue happen when current thread try to close the ResultSet. SC doesn't need the ResultSet, so the ResultSet.close() doesn't affect it. I think it is fixed from SC 2.7.2
